language: node_js
node_js:
  - "8"
  - "7"
  - "6"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

before_script:
  - npm prune

script:
  - npm run lint
  - npm test

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ; fi
