environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version

before_build:
  - npm install
  - npm prune

build_script:
  - npm run lint
  - npm test
  - npm run build

test: off

cache:
  - node_modules
